### ISSUE TITLE
Create list of launches

### ISSUE THREAD

**Issue by vmonjaret** [haas36u/spaceX#14]
# Launch list

## TODO

- [x] Implement a component list to list all launches
- [x] Implement a component for a single launch (like a thumbnail)
- [x] Add buttons to choose launches (All | Past | Upcoming)

## How to demo

When I click on launches in the navigation drawer
I should see the list of all launches with the button *All* highlighted
If I click on *Past* I should see the past launches and this button should be highlighted
If I click on *Upcoming* I should see the upcoming launches and this button should be highlighted
